---
- name: Install DNF Copr command
  ansible.builtin.dnf:
    name: dnf-command(copr)
    state: latest

- name: Enable caddy copr
  community.general.copr:
    state: enabled
    name: "@caddy/caddy"

- name: Install caddy
  ansible.builtin.dnf:
    name: caddy
    state: latest

- name: Enable and start caddy.service
  ansible.builtin.systemd:
    name: caddy.service
    state: started
    enabled: true

- name: Allow HTTP(s) traffic in firewalld
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
  notify:
    - Reload firewalld.service
  with_items:
    - http
    - https
    - http3

- name: Copy caddy.conf jail
  ansible.builtin.copy:
    src: jail_caddy.conf
    dest: /etc/fail2ban/jail.d/caddy.conf
    mode: "0640"
  notify:
    - Reload fail2ban.service

- name: Copy caddy.conf filter
  ansible.builtin.copy:
    src: filter_caddy.conf
    dest: /etc/fail2ban/filter.d/caddy.conf
    mode: "0640"
  notify:
    - Reload fail2ban.service

- name: Create caddy directories
  ansible.builtin.file:
    state: directory
    path: /etc/caddy/{{ item }}
    mode: "0755"
  with_items:
    - helpers
    - sites

- name: Copy main Caddyfile
  ansible.builtin.copy:
    src: Caddyfile
    dest: /etc/caddy/Caddyfile
    mode: "0755"

- name: Copy caddy helpers
  ansible.builtin.copy:
    src: "{{ item }}.caddyfile"
    dest: /etc/caddy/helpers/{{ item }}.caddyfile
    mode: "0755"
  with_items:
    - log
    - errors

- name: Create caddy log directory
  ansible.builtin.file:
    path: /var/log/caddy
    state: directory
    mode: "0755"
    owner: caddy
    group: caddy
