---
extends: default

rules:
  braces:
    forbid: non-empty
  brackets:
    forbid: non-empty
  commas:
    min-spaces-after: 1
    max-spaces-after: 1
  empty-values: enable
  indentation:
    spaces: 2
  line-length:
    max: 100
    level: warning
  quoted-strings:
    quote-type: double
    required: only-when-needed

locale: en_US.UTF-8
