---
collections:
  - community.general

roles:
  - name: konstruktoid.docker_rootless
    src: https://github.com/konstruktoid/ansible-role-docker-rootless
    version: v0.61.0
  - name: borgbase.ansible_role_borgbackup
    src: https://github.com/borgbase/ansible-role-borgbackup
    version: v1.1.3
