---
collections:
  - community.general

roles:
  - name: konstruktoid.docker_rootless
    src: https://github.com/woomymy/ansible-role-docker-rootless
    version: 35df842c0728a4f3ef445c5377d0fc2f14d4f341
  - name: borgbase.ansible_role_borgbackup
    src: https://github.com/borgbase/ansible-role-borgbackup
    version: v1.1.3
