---
services:
  app:
    image: freshrss/freshrss:1.26.3-alpine
    restart: always
    env_file: .env
    volumes:
      - freshrss-data:/var/www/FreshRSS/data
      - freshrss-extensions:/var/www/FreshRSS/extensions
    ports:
      - 127.0.0.1:3001:80

volumes:
  freshrss-data:
    driver: local
  freshrss-extensions:
    driver: local
