---
services:
  bot:
    image: ghcr.io/federation-interservices-d-informatique/fiibot-id:1.4.0
    env_file: .env
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - db

  db:
    image: postgres:17.6-alpine
    env_file: .env
    restart: always
    ports:
      - 127.0.0.1:6903:5432
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - fiibot-id-postgres:/var/lib/postgresql/data

volumes:
  fiibot-id-postgres:
    driver: local
