---
- name: Install fuse-overlayfs
  ansible.builtin.dnf:
    name: fuse-overlayfs
    state: latest

- name: Include the konstruktoid.docker_rootless role (configure docker)
  ansible.builtin.import_role:
    name: konstruktoid.docker_rootless
  vars:
    docker_compose: true
    docker_allow_privileged_ports: true
    docker_rootless_service_template: docker_rootless.service.custom.j2

- name: Set services homedir variable
  ansible.builtin.set_fact:
    services_homedir: "{{ docker_user_info.home }}/{{ services_dirname }}"

- name: Create a directory for docker compose files
  become: true
  become_user: "{{ docker_user }}"
  ansible.builtin.file:
    path: "{{ services_homedir }}"
    state: directory
    mode: "0700"

- name: Add DOCKER_HOST and XDG_RUNTIME_DIR to .profile
  become: true
  become_user: "{{ docker_user }}"
  ansible.builtin.copy:
    dest: "{{ docker_user_info.home }}/.profile"
    mode: "0755"
    content: |
      export DOCKER_HOST=unix:///run/user/{{ docker_user_info.uid }}/docker.sock
      export XDG_RUNTIME_DIR=/run/user/{{ docker_user_info.uid }}

- name: Source .profile from bashrc
  become: true
  become_user: "{{ docker_user }}"
  ansible.builtin.lineinfile:
    path: "{{ docker_user_info.home }}/.bashrc"
    line: source ~/.profile
    create: true
    mode: "0755"
