---
- name: Install fuse-overlayfs
  ansible.builtin.dnf:
    name: fuse-overlayfs
    state: latest

- name: Include the konstruktoid.docker_rootless role (configure docker)
  ansible.builtin.import_role:
    name: konstruktoid.docker_rootless
  vars:
    docker_compose: true
    docker_allow_privileged_ports: true
    docker_rootless_service_template: docker_rootless.service.custom.j2
    docker_compose_arch: aarch64
    docker_url: https://download.docker.com/linux/static/stable/aarch64
    docker_release_shasum: 836bbaea204251922ec4dc79dbe81e323ccedaa726efc01f62683f547d721871
    docker_release_rootless_shasum: 9a98aded51f811260aac894845cef194d62ef4381520db9486f7a9094d692844
    docker_compose_release_shasum: a91e930a076b91e6c69f11d1dbe3c06729ae765fb9dbb3f97cb808e784647399

- name: Set services homedir variable
  ansible.builtin.set_fact:
    services_homedir: "{{ docker_user_info.home }}/{{ services_dirname }}"

- name: Create a directory for docker compose files
  become: true
  become_user: "{{ docker_user }}"
  ansible.builtin.file:
    path: "{{ services_homedir }}"
    state: directory
    mode: "0700"

- name: Add DOCKER_HOST and XDG_RUNTIME_DIR to .profile
  become: true
  become_user: "{{ docker_user }}"
  ansible.builtin.copy:
    dest: "{{ docker_user_info.home }}/.profile"
    mode: "0755"
    content: |
      export DOCKER_HOST=unix:///run/user/{{ docker_user_info.uid }}/docker.sock
      export XDG_RUNTIME_DIR=/run/user/{{ docker_user_info.uid }}

- name: Source .profile from bashrc
  become: true
  become_user: "{{ docker_user }}"
  ansible.builtin.lineinfile:
    path: "{{ docker_user_info.home }}/.bashrc"
    line: source ~/.profile
    create: true
    mode: "0755"
