---
- name: Install FirewallD
  ansible.builtin.dnf:
    name: firewalld
    state: latest

- name: Enable and start firewalld.service
  ansible.builtin.systemd:
    name: firewalld.service
    state: started
    enabled: true
