---
- name: Allow SSHD to listen on ssh port
  community.general.seport:
    ports: "{{ sshd_port }}"
    proto: tcp
    setype: ssh_port_t
    state: present

- name: Open SSH port
  ansible.posix.firewalld:
    port: "{{ sshd_port }}/tcp"
    permanent: true
    state: enabled
  notify:
    - Reload firewalld.service

- name: Copy sshd configuration
  ansible.builtin.template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    mode: "0600"
  notify:
    - Reload sshd.service

- name: Create the .ssh directory
  ansible.builtin.file:
    path: "{{ item.home }}/.ssh"
    state: directory
    mode: "0700"
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
  loop: "{{ system_users_info.results }}"

- name: Add my key to authorized_keys
  ansible.builtin.copy:
    src: authorized_keys
    dest: "{{ item.home }}/.ssh/authorized_keys"
    mode: "0600"
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
  loop: "{{ system_users_info.results }}"

- name: Install fail2ban configuration
  ansible.builtin.template:
    src: sshd_fail2ban.conf.j2
    dest: /etc/fail2ban/jail.d/sshd.conf
    mode: "0640"
  notify:
    - Reload fail2ban.service
