---
services:
  app:
    image: codeberg.org/forgejo/forgejo:1.21.6-0-rootless
    env_file: .env
    restart: always
    volumes:
      - forgejo-data:/var/lib/gitea
      - ./config:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - forgejo
    depends_on:
      - db

  db:
    image: postgres:16.2-alpine
    env_file: .env
    restart: always
    networks:
      - forgejo
    volumes:
      - forgejo-postgres:/var/lib/postgresql/data

volumes:
  forgejo-data:
    driver: local
  forgejo-config:
    driver: local
  forgejo-postgres:
    driver: local

networks:
  forgejo:
    external: false
