---
services:
  app:
    image: codeberg.org/forgejo/forgejo:7.0.2-rootless
    env_file: .env
    restart: always
    volumes:
      - forgejo-data:/var/lib/gitea
      - ./config:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 127.0.0.1:3000:3000
      - 22:2222
    depends_on:
      - db

  db:
    image: postgres:16.4-alpine
    env_file: .env
    restart: always
    volumes:
      - forgejo-postgres:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:6900:5432

volumes:
  forgejo-data:
    driver: local
  forgejo-config:
    driver: local
  forgejo-postgres:
    driver: local
