---
- name: Enable dnf fastestmirror
  community.general.ini_file:
    path: /etc/dnf/dnf.conf
    section: main
    option: fastestmirror
    value: true
    mode: 644

- name: Update dependencies
  ansible.builtin.dnf:
    name: "*"
    state: latest

# `setfacl` is needed by Ansible
- name: Install ACL
  ansible.builtin.dnf:
    name: "acl"
    state: latest
