---
- name: Create the sudo group
  ansible.builtin.group:
    name: sudo

- name: Register system users info
  ansible.builtin.user:
    name: "{{ item }}"
    shell: /bin/bash
    groups: sudo, systemd-journal, wheel
    append: true
    password: "{{ users_passwords[user_idx] }}"
  register: system_users_info
  loop: "{{ system_users }}"
  loop_control:
    index_var: user_idx

- name: Register Docker user info
  ansible.builtin.user:
    name: "{{ docker_user }}"
    shell: /bin/bash
  register: docker_user_info
