---
- name: Install git
  ansible.builtin.dnf:
    name: git
    state: latest

- name: Set static dir path
  ansible.builtin.set_fact:
    static_path: /var/www

- name: Setup dir for static pages
  ansible.builtin.file:
    state: directory
    path: "{{ static_path }}"
    mode: "0775"
    owner: "{{ woomy_user }}"
    group: www-data

- name: Clone pages
  become: true
  become_user: "{{ woomy_user }}"
  ansible.builtin.git:
    repo: https://github.com/Woomymy/{{ item }}
    dest: "{{ static_path }}/{{ item }}"
  with_items:
    - "{{ woomy_domain }}"
    - custom_pages

- name: Create well-known dirs
  become: true
  become_user: "{{ woomy_user }}"
  ansible.builtin.file:
    state: directory
    path: "{{ static_path }}/well-known/openpgpkey/hu/"
    mode: "0775"
    recurse: true
    group: www-data

- name: Create openpgp policy file
  become: true
  become_user: "{{ woomy_user }}"
  ansible.builtin.copy:
    content: ""
    dest: "{{ static_path }}/well-known/openpgpkey/policy"
    mode: "0775"
    group: www-data

- name: Copy openpgp file
  become: true
  become_user: "{{ woomy_user }}"
  ansible.builtin.copy:
    src: mscrnig88g4mzagk5ytb4ioz7yg51f67
    dest: "{{ static_path }}/well-known/openpgpkey/hu/mscrnig88g4mzagk5ytb4ioz7yg51f67"
    mode: "0775"
    group: www-data

- name: Create files.woomy.be directories
  become: true
  become_user: "{{ woomy_user }}"
  ansible.builtin.file:
    path: "{{ static_path }}/files"
    state: directory
    mode: "0775"
    group: www-data

- name: Install static caddy config
  ansible.builtin.template:
    src: static.caddyfile.j2
    dest: /etc/caddy/sites/static.caddyfile
    mode: "0775"
  notify:
    - Restart caddy.service

- name: Fix SELinux context
  ansible.builtin.command: restorecon -ivR {{ static_path }}
  register: restorecon_result
  changed_when: restorecon_result.stdout != ""
