---
- name: Set services home path
  ansible.builtin.set_fact:
    nextcloud_dir: "{{ services_homedir }}/nextcloud"

- name: Create nextcloud docker-compose directory
  become: true
  become_user: "{{ docker_user }}"
  ansible.builtin.file:
    path: "{{ nextcloud_dir }}"
    state: directory
    mode: "0755"

- name: Copy docker-compose.yml
  become: true
  become_user: "{{ docker_user }}"
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: "{{ nextcloud_dir }}/docker-compose.yml"
    mode: "0755"

- name: Copy env file
  become: true
  become_user: "{{ docker_user }}"
  ansible.builtin.template:
    src: env.j2
    dest: "{{ nextcloud_dir }}/.env"
    mode: "0755"

- name: Copy fpm caddyfile
  become: true
  become_user: "{{ docker_user }}"
  ansible.builtin.template:
    src: docker.Caddyfile
    dest: "{{ nextcloud_dir }}/Caddyfile"
    mode: "0755"

- name: Copy caddy site configuration
  ansible.builtin.template:
    src: nextcloud.caddyfile
    dest: /etc/caddy/sites/nextcloud.caddyfile
    mode: "0755"
  notify:
    - Restart caddy.service

- name: Install nextcloud cron service
  become: true
  become_user: "{{ docker_user }}"
  ansible.builtin.template:
    src: nextcloud-cron.service
    dest: "{{ docker_user_info.home }}/.config/systemd/user/nextcloud-cron.service"
    mode: "0600"

- name: Install nextcloud cron timer
  become: true
  become_user: "{{ docker_user }}"
  ansible.builtin.template:
    src: nextcloud-cron.timer
    dest: "{{ docker_user_info.home }}/.config/systemd/user/nextcloud-cron.timer"
    mode: "0600"

- name: Start nextcloud
  become: true
  become_user: "{{ docker_user }}"
  environment:
    XDG_RUNTIME_DIR: /run/user/{{ docker_user_info.uid }}
    PATH: "{{ docker_user_info.home }}/bin:{{ ansible_env.PATH }}"
    DOCKER_HOST: unix:///run/user/{{ docker_user_info.uid }}/docker.sock
  community.docker.docker_compose_v2:
    project_src: "{{ nextcloud_dir }}"
    state: present
    remove_orphans: true

- name: Enable and start nextcloud cron timer
  become: true
  become_user: "{{ docker_user }}"
  ansible.builtin.systemd:
    name: nextcloud-cron.timer
    enabled: true
    state: started
    scope: user
    daemon_reload: true
