---
- name: Set services home path
  ansible.builtin.set_fact:
    nextcloud_dir: "{{ services_homedir }}/nextcloud"

- name: Create nextcloud docker-compose directory
  become: true
  become_user: "{{ docker_user }}"
  ansible.builtin.file:
    path: "{{ nextcloud_dir }}"
    state: directory
    mode: "0755"

- name: Copy docker-compose.yml
  become: true
  become_user: "{{ docker_user }}"
  ansible.builtin.copy:
    src: "docker-compose.yml"
    dest: "{{ nextcloud_dir }}/docker-compose.yml"
    mode: "0755"

- name: Copy env file
  become: true
  become_user: "{{ docker_user }}"
  ansible.builtin.template:
    src: "env.j2"
    dest: "{{ nextcloud_dir }}/.env"
    mode: "0755"

- name: Copy caddy site configuration
  ansible.builtin.copy:
    src: "nextcloud.woomy.be.Caddyfile"
    dest: "/etc/caddy/sites/nextcloud.woomy.be.Caddyfile"
    mode: "0755"
  notify:
    - Restart caddy.service

- name: Start nextcloud
  become: true
  become_user: "{{ docker_user }}"
  environment:
    XDG_RUNTIME_DIR: /run/user/{{ docker_user_info.uid }}
    PATH: "{{ docker_user_info.home }}/bin:{{ ansible_env.PATH }}"
    DOCKER_HOST: "unix:///run/user/{{ docker_user_info.uid }}/docker.sock"
  community.docker.docker_compose_v2:
    project_src: "{{ nextcloud_dir }}"
    state: present
    remove_orphans: true
