---
# PostgreSQL is needed by borg for running pg_dump
- name: Install PostgreSQL
  ansible.builtin.dnf:
    name: postgresql18
    state: latest

# Build dependency
- name: Install python-devel
  ansible.builtin.dnf:
    name: python3-devel
    state: latest

- name: Setup borg backup
  ansible.builtin.import_role:
    name: borgbase.ansible_role_borgbackup
  vars:
    borgbackup_timer:
      type: systemd
      hour: 03
      minute: 05
    borgbackup_install:
      method: package
    borgbackup_config:
      encryption_passphrase: "{{ borg_config.encryption_passphrase }}"
      repositories: "{{ borg_config.repositories }}"
      source_directories:
        - "{{ docker_user_info.home }}/.local/share/docker/volumes/"
        - /var/www/files
      # We backup postgres databases using hooks
      exclude_patterns:
        - sh:{{ docker_user_info.home }}/.local/share/docker/volumes/*-postgres*
      extra:
        ntfy:
          topic: "{{ borg_ntfy_topic }}"
          server: "{{ borg_ntfy_server }}"
          fail:
            title: Echec de la sauvegarde
            message: La sauvegarde borgmatic ne s'est pas passee correctement
            tags: borgmatic,skull
            priority: max
          states:
            - fail
      hooks:
        postgresql_databases:
          - name: nextcloud
            hostname: 127.0.0.1
            port: 6902
            password: "{{ nextcloud_postgres_pw }}"
            username: nextcloud
          - name: fiibot-id
            hostname: 127.0.0.1
            port: 6903
            password: "{{ fiibot_id_postgres_pw }}"
            username: fiibot-id
          - name: fiibot-interservers
            hostname: 127.0.0.1
            port: 6904
            password: "{{ fiibot_interservers_postgres_pw }}"
            username: fiibot-interservers
          - name: fiibot-logger
            hostname: 127.0.0.1
            port: 6905
            password: "{{ fiibot_logger_postgres_pw }}"
            username: fiibot-logger
          - name: fiibot-moderation
            hostname: 127.0.0.1
            port: 6906
            password: "{{ fiibot_moderation_postgres_pw }}"
            username: fiibot-moderation
        commands:
          - before: action
            when:
              - create
            run:
              - echo "`date` - Starting backup"
          - after: everything
            run:
              - echo "`date` - Finished backup"
              - ssh -p {{ borg_ssh_port }} {{ borg_ssh_user }}@{{ borg_ssh_host }} 'sudo poweroff'

- name: Start and enable borgmatic.timer
  ansible.builtin.systemd:
    name: borgmatic.timer
    state: started
    enabled: true

- name: Copy host key to known_hosts
  ansible.builtin.copy:
    content: "{{ borg_host_key }}"
    dest: /root/.ssh/known_hosts
    mode: "0600"
