---
# PostgreSQL is needed by borg for running pg_dump
- name: Install PostgreSQL
  ansible.builtin.dnf:
    name: postgresql16
    state: latest

- name: Install cronie
  ansible.builtin.dnf:
    name: cronie
    state: latest

- name: Setup borg backup
  ansible.builtin.import_role:
    name: borgbase.ansible_role_borgbackup
  vars:
    borgmatic_timer: systemd
    borgmatic_timer_hour: 03
    borgmatic_timer_minute: 05
    borg_source_directories:
      - "{{ docker_user_info.home }}/.local/share/docker/volumes/"
      - /var/www/files
    # We backup postgres databases using hooks
    borg_exclude_patterns:
      - sh:{{ docker_user_info.home }}/.local/share/docker/volumes/*-postgres*
    borgmatic_hooks:
      before_backup:
        - echo "`date` - Starting backup."
      after_everything:
        - echo "`date` - Finished backup."
        - "ssh -p {{ borg_ssh_port }} {{ borg_ssh_user }}@{{ borg_ssh_host }} 'sudo poweroff'"
      postgresql_databases:
        - name: gitea
          hostname: 127.0.0.1
          port: 6900
          password: "{{ gitea_postgres_pw }}"
          username: gitea
        - name: joplin
          hostname: 127.0.0.1
          port: 6901
          password: "{{ joplin_postgres_pw }}"
          username: joplin
        - name: nextcloud
          hostname: 127.0.0.1
          port: 6902
          password: "{{ nextcloud_postgres_pw }}"
          username: nextcloud
        - name: fiibot-id
          hostname: 127.0.0.1
          port: 6903
          password: "{{ fiibot_id_postgres_pw }}"
          username: fiibot-id
        - name: fiibot-interservers
          hostname: 127.0.0.1
          port: 6904
          password: "{{ fiibot_interservers_postgres_pw }}"
          username: fiibot-interservers
        - name: fiibot-logger
          hostname: 127.0.0.1
          port: 6905
          password: "{{ fiibot_logger_postgres_pw }}"
          username: fiibot-logger
        - name: fiibot-moderation
          hostname: 127.0.0.1
          port: 6906
          password: "{{ fiibot_moderation_postgres_pw }}"
          username: fiibot-moderation

- name: Start borgmatic.timer
  ansible.builtin.systemd:
    name: borgmatic.timer
    state: started

- name: Enable borgmatic.timer
  ansible.builtin.systemd:
    name: borgmatic.timer
    enabled: true

- name: Copy host key to known_hosts
  ansible.builtin.copy:
    content: "{{ borg_host_key }}"
    dest: /root/.ssh/known_hosts
    mode: "0600"
