---
# PostgreSQL is needed by borg for running pg_dump
- name: Install PostgreSQL
  ansible.builtin.dnf:
    name: "postgresql16"
    state: latest

- name: Install cronie
  ansible.builtin.dnf:
    name: "cronie"
    state: latest

- name: Setup borg backup
  ansible.builtin.import_role:
    name: borgbase.ansible_role_borgbackup
  vars:
    borgmatic_timer: systemd
    borgmatic_timer_hour: 17
    borgmatic_timer_minute: 30
    borg_source_directories:
      - "{{ docker_user_info.home }}/.local/share/docker/volumes/"
      - /var/www/files
    # We backup postgres databases using hooks
    borg_exclude_patterns:
      - 'sh:{{ docker_user_info.home }}/.local/share/docker/volumes/*-postgres*'
    borgmatic_hooks:
      before_backup:
        - echo "`date` - Starting backup."
      after_everything:
        - echo "`date` - Finished backup."
      #  - "ssh -p {{ borg_port }} {{ borg_user }}@{{ borg_host }} 'sudo poweroff'"
      postgresql_databases:
        - name: gitea
          hostname: 127.0.0.1
          port: 6900
          password: "{{ gitea_postgres_pw }}"
          username: gitea
        - name: joplin
          hostname: 127.0.0.1
          port: 6901
          password: "{{ joplin_postgres_pw }}"
          username: joplin

- name: Start borgmatic.timer
  ansible.builtin.systemd:
    name: "borgmatic.timer"
    state: started

- name: Enable borgmatic.timer
  ansible.builtin.systemd:
    name: "borgmatic.timer"
    enabled: true
