---
- name: Install python-libdnf5
  ansible.builtin.command: dnf install python-libdnf5 -y
  register: libpython_result
  changed_when: "'is already installed' not in libpython_result.stderr"

- name: Enable dnf fastestmirror
  community.general.ini_file:
    path: /etc/dnf/dnf.conf
    section: main
    option: fastestmirror
    value: true
    mode: 644

- name: Update dependencies
  ansible.builtin.dnf:
    name: "*"
    state: latest

# `setfacl` is needed by Ansible
- name: Install ACL and dnf-automatic
  ansible.builtin.dnf:
    name:
      - acl
      - dnf5-plugin-automatic
    state: latest

- name: Enable automatic updates application
  community.general.ini_file:
    path: /etc/dnf/automatic.conf
    section: commands
    option: apply_updates
    value: true
    mode: 644

- name: Enable reboot when needed
  community.general.ini_file:
    path: /etc/dnf/automatic.conf
    section: commands
    option: reboot
    value: when-needed
    mode: 644

- name: Start and enable dnf-automatic.timer
  ansible.builtin.systemd:
    name: dnf-automatic.timer
    state: started
    enabled: true
