---
- name: Enable dnf fastestmirror
  community.general.ini_file:
    path: /etc/dnf/dnf.conf
    section: main
    option: fastestmirror
    value: true
    mode: 644

- name: Update dependencies
  ansible.builtin.dnf:
    name: "*"
    state: latest

# `setfacl` is needed by Ansible
- name: Install ACL
  ansible.builtin.dnf:
    name: "acl"
    state: latest

- name: Install dnf-automatic
  ansible.builtin.dnf:
    name: dnf-automatic
    state: latest

- name: Enable automatic updates application
  community.general.ini_file:
    path: /etc/dnf/automatic.conf
    section: commands
    option: apply_updates
    value: true
    mode: 644

- name: Enable reboot when needed
  community.general.ini_file:
    path: /etc/dnf/automatic.conf
    section: commands
    option: reboot
    value: when-needed
    mode: 644

- name: Enable dnf-automatic.timer
  ansible.builtin.systemd:
    name: dnf-automatic.timer
    enabled: true

- name: Start dnf-automatic.timer
  ansible.builtin.systemd:
    name: dnf-automatic.timer
    state: started
