---
- name: Set services home path
  ansible.builtin.set_fact:
    forgejo_dir: "{{ services_homedir }}/forgejo"

- name: Create forgejo docker-compose directory
  become: true
  become_user: "{{ docker_user }}"
  ansible.builtin.file:
    path: "{{ forgejo_dir }}"
    state: directory
    mode: "0755"

- name: Check if docker-compose.yml already exists
  ansible.builtin.stat:
    path: "{{ forgejo_dir }}/docker-compose.yml"
  register: docker_compose_yml

# We must stop forgejo before modifying the docker-compose.yml file
- name: Ensure forgejo is stopped
  become: true
  become_user: "{{ docker_user }}"
  environment:
    XDG_RUNTIME_DIR: /run/user/{{ docker_user_info.uid }}
    PATH: "{{ docker_user_info.home }}/bin:{{ ansible_env.PATH }}"
    DOCKER_HOST: "unix:///run/user/{{ docker_user_info.uid }}/docker.sock"
  community.docker.docker_compose_v2:
    project_src: "{{ forgejo_dir }}"
    state: absent
  when: docker_compose_yml.stat.exists

- name: Copy docker-compose.yml
  become: true
  become_user: "{{ docker_user }}"
  ansible.builtin.copy:
    src: "docker-compose.yml"
    dest: "{{ forgejo_dir }}/docker-compose.yml"
    mode: "0755"

- name: Copy env file
  become: true
  become_user: "{{ docker_user }}"
  ansible.builtin.template:
    src: "env.j2"
    dest: "{{ forgejo_dir }}/.env"
    mode: "0755"

- name: Copy caddy site configuration
  ansible.builtin.copy:
    src: "git.woomy.be.Caddyfile"
    dest: "/etc/caddy/sites/git.woomy.be.Caddyfile"
    mode: "0755"
  notify:
    - Restart caddy.service

- name: Create gitea configuration dir
  become: true
  become_user: "{{ docker_user }}"
  ansible.builtin.file:
    path: "{{ forgejo_dir }}/config"
    state: directory
    mode: "0755"

- name: Copy app.ini
  become: true
  become_user: "{{ docker_user }}"
  ansible.builtin.template:
    src: app.ini.j2
    dest: "{{ forgejo_dir }}/config/app.ini"
    mode: "0755"

- name: Start forgejo
  become: true
  become_user: "{{ docker_user }}"
  environment:
    XDG_RUNTIME_DIR: /run/user/{{ docker_user_info.uid }}
    PATH: "{{ docker_user_info.home }}/bin:{{ ansible_env.PATH }}"
    DOCKER_HOST: "unix:///run/user/{{ docker_user_info.uid }}/docker.sock"
  community.docker.docker_compose_v2:
    project_src: "{{ forgejo_dir }}"
    state: present
