services:
  bot:
    image: ghcr.io/federation-interservices-d-informatique/fiibot-interservers:1.1.5
    env_file: .env
    restart: always
    networks:
      - fiibot-interservers
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    depends_on:
      - db

  db:
    image: postgres:16.2-alpine
    env_file: .env
    restart: always
    networks:
      - fiibot-interservers
    ports:
      - "127.0.0.1:6904:5432"
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "fiibot-interservers-postgres:/var/lib/postgresql/data"

volumes:
  fiibot-interservers-postgres:
    driver: local

networks:
  fiibot-interservers:
    external: false
