---
- name: Install fail2ban
  ansible.builtin.dnf:
    name: fail2ban
    state: latest

- name: Enable and start fail2ban.service
  ansible.builtin.systemd:
    name: fail2ban.service
    state: started
    enabled: true
