---
- name: Setup everything
  hosts: all
  become: true
  vars:
    # System
    domain: woomy.be
    domain_2: colle.dev
    system_users: 
      - woomy
      - polyrhachis

    docker_user: docker
    services_dirname: services

    # Joplin
    joplin_proto: https
    joplin_domain: joplin.{{ domain }}
    joplin_mailer_noreply: joplin@{{ domain }}

    # NextCloud
    nextcloud_domain: nextcloud.{{ domain }}
    nextcloud_trusted_domains: www.{{ nextcloud_domain }} {{ nextcloud_domain }}
    nextcloud_mail_from: nextcloud

    # Vaultwarden
    vaultwarden_proto: https
    vaultwarden_domain: bitwarden.{{ domain }}
    vaultwarden_smtp_from: vaultwarden@{{ domain }}
  roles:
    - timezone
    - hostname
    - dnf
    - users
    - journal
    - firewall
    - fail2ban
    - sshd_config
    - caddy
    - docker
    - vaultwarden
    - joplin
    - static
    - nextcloud
    - fiibot_id
    - fiibot_interservers
    - fiibot_logger
    - fiibot_moderation
    - fiibot_tm
    - borg
