---
- name: Setup everything
  hosts: all
  become: true
  vars:
    # System
    system_user: woomy
    docker_user: docker
    sshd_port: 22
    services_dirname: services

    # Forgejo
    gitea_app_name: "Woomy's git"
    gitea_domain: git.woomy.be
    gitea_proto: http
    gitea_mailer_from_email: "gitea@woomy.be"

    # Joplin
    joplin_domain: joplin.woomy.be
    joplin_proto: http
    joplin_mailer_noreply: "joplin@woomy.be"

    # NextCloud
    nextcloud_trusted_domains: nextcloud.woomy.be
    nextcloud_mail_from: nextcloud

    # Vaultwarden
    vaultwarden_proto: http
    vaultwarden_domain: bitwarden.woomy.be
    vaultwarden_smtp_from: "vaultwarden@woomy.be"
  roles:
    - timezone
    - dnf
    - users
    - firewall
    - fail2ban
    - sshd_config
    - caddy
    - docker
    - forgejo
    - freshrss
    - vaultwarden
    - joplin
    - static
    - nextcloud
    - borg
