---
- name: Setup everything
  hosts: all
  become: true
  vars:
    # System
    woomy_domain: woomy.be
    colle_domain: colle.dev
    woomy_user: woomy
    system_users:
      - woomy
      - polyrhachis

    docker_user: docker
    services_dirname: services

    # Joplin
    joplin_proto: https
    joplin_main_domain: joplin.{{ woomy_domain }}
    joplin_all_domains: www.{{ joplin_main_domain }} joplin.{{ colle_domain }}
    joplin_mailer_noreply: joplin@{{ woomy_domain }}

    # NextCloud
    nextcloud_domain: nextcloud.{{ woomy_domain }}
    nextcloud_trusted_domains: www.{{ nextcloud_domain }} nextcloud.{{ colle_domain }}
    nextcloud_mail_from: nextcloud

    # Vaultwarden
    vaultwarden_proto: https
    vaultwarden_main_domain: bitwarden.{{ woomy_domain }}
    vaultwarden_all_domains: www.bitwarden.{{ woomy_domain }}
    vaultwarden_smtp_from: vaultwarden@{{ woomy_domain }}
  roles:
    - timezone
    - hostname
    - dnf
    - users
    - journal
    - firewall
    - fail2ban
    - sshd_config
    - caddy
    - docker
    - vaultwarden
    - joplin
    - static
    - nextcloud
    - fiibot_id
    - fiibot_interservers
    - fiibot_logger
    - fiibot_moderation
    - borg
