---
- name: Setup basic services (before port changes)
  hosts: all
  become: true
  vars:
    # System
    woomy_domain: woomy.be
    colle_domain: colle.dev
    woomy_user: woomy
    system_users: 
      - woomy
      - polyrhachis

    docker_user: docker
    services_dirname: services

  roles:
    - timezone
    - hostname
    - dnf
    - users
    - journal
    - firewall
    - fail2ban
    - sshd_config
