---
services:
  app:
    image: nextcloud:33.0.0-fpm-alpine
    restart: always
    env_file: .env
    volumes:
      - nextcloud-data:/var/www/html
      - ./php-fpm-tuning.conf:/usr/local/etc/php-fpm.d/zz-php-fpm-tuning.conf:ro
    depends_on:
      - db
      - redis
  caddy:
    image: caddy:2.11.2-alpine
    restart: always
    volumes:
      - nextcloud-data:/var/www/html:ro
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    ports:
      - 3004:80
  db:
    image: postgres:18.3-alpine
    restart: always
    env_file: .env
    ports:
      - 127.0.0.1:6902:5432
    volumes:
      - nextcloud-postgres:/var/lib/postgresql
  redis:
    image: valkey/valkey:9.0.3-alpine
    restart: always

volumes:
  nextcloud-data:
    driver: local
  nextcloud-postgres:
    driver: local
