---
name: Ansible Lint

on:
  push:
  pull_request:

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
          cache: 'pip'
      - name: Install dependencies
        run: |
          pip install ansible ansible-lint yamllint
      - name: Run ansible-lint
        run: |
          ansible-lint
